config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  get '/auth/github/callback', to: 'sessions#create'
  get '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  resources :users, only: [:show]
  resources :repos, only: [:index]
  resources :stars, only: [:index]
  resources :followers, only: [:index]
  resources :following, only: [:index]
  resources :gists, only: [:index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_commit.rb
class GithubCommit
  attr_reader :repo, :payload, :repo_name, :message_hash

  def initialize(attributes = {})
    @repo = attributes[:repo]
    @payload = attributes[:payload]
    @repo_name = attributes[:repo][:name]
    @message_hash = attributes[:payload][:commits]
  end

  def self.for_user(username)
    GithubService.new.all_commits_by_user(username).map do |item|
      GithubCommit.new(item)
    end
  end

  def self.get_commit_message(commits)
    messages = []
    commits.each do |commit|
      commit.message_hash.each do |message|
        messages << message[:message]
      end
    end
    messages
  end

end

app/models/github_follower.rb
class GithubFollower
  attr_reader :login, :avatar

  def initialize(attributes = {})
    @login = attributes[:login]
    @avatar = attributes[:avatar_url]
  end

  def self.for_user(user)
    GithubService.new.followers(user).map do |follower_list|
      GithubFollower.new(follower_list)
    end
  end

end

app/models/github_following.rb
class GithubFollowing
  attr_reader :login, :avatar

  def initialize(attributes = {})
    @login = attributes[:login]
    @avatar = attributes[:avatar_url]
  end

  def self.for_user(user)
    GithubService.new.following(user).map do |follower_list|
      GithubFollowing.new(follower_list)
    end
  end

end

app/models/github_repo.rb
class GithubRepo
  attr_reader :name, :full_name, :description, :language, :updated_at

  def initialize(attributes = {})
    @name = attributes[:name]
    @language = attributes[:language]
    @description = attributes[:description]
    @updated_at = attributes[:updated_at]
  end

  def self.for_user(user)
    GithubService.new.user_repos(user).map do |raw_repo|
      GithubRepo.new(raw_repo)
    end
  end

  def date_format(date_string)
    date = date_string.to_datetime
    date.strftime("%b %e")
  end

end

app/models/github_star.rb
class GithubStar
  attr_reader :full_name, :full_name, :description, :language, :updated_at

  def initialize(attributes = {})
    @full_name = attributes[:full_name]
    @language = attributes[:language]
    @description = attributes[:description]
    @updated_at = attributes[:updated_at]
  end

  def self.for_user(user)
    GithubService.new.starred(user).map do |raw_repo|
      GithubStar.new(raw_repo)
    end
  end

  def date_format(date_string)
    date = date_string.to_datetime
    date.strftime("%b %e")
  end

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def index
    user = User.find(current_user.id)
    @followers = GithubFollower.for_user(user)
  end

end

app/controllers/following_controller.rb
class FollowingController < ApplicationController

  def index
    user = User.find(current_user.id)
    @followers = GithubFollowing.for_user(user)
  end

end

app/controllers/gists_controller.rb
class GistsController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/repos_controller.rb
class ReposController < ApplicationController

  def index
    user = User.find(current_user.id)
    @user_repos = GithubRepo.for_user(user)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    response = Faraday.post("https://github.com/login/oauth/access_token?client_id=#{ENV["github_client_id"]}&client_secret=#{ENV["github_client_secret"]}&code=#{params["code"]}")
    token = response.body.split(/\W+/)[1]
    oauth_response = Faraday.get("https://api.github.com/user?access_token=#{token}")
    auth = JSON.parse(oauth_response.body)

    user = User.find_or_create_by(uid: auth["id"])
    user.username = auth["login"]
    user.uid = auth["id"]
    user.name = auth["name"]
    user.location = auth["location"]
    user.email = auth["email"]
    user.token = token
    user.save

    session[:user_id] = user.id

    redirect_to user_path(user)
  end

  def destroy
    session.delete(:user_id)

    redirect_to root_path
  end

end

app/controllers/stars_controller.rb
class StarsController < ApplicationController

  def index
    user = User.find(current_user.id)
    @starred_repos = GithubStar.for_user(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    user = User.find(current_user.id)
    @user_commits = GithubCommit.for_user(user.username)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/followers/index.html.erb
<div class="container container-profile">

  <div class="col-md-3">
    <%= render 'layouts/user_bar' %>
  </div>
  <div class="col-md-9">
    <%= render 'layouts/tabs' %>

    <div class="feed">
        <%= render 'layouts/follower' %>
      </div>
  </div>
</div>

app/views/following/index.html.erb
<div class="container container-profile">

  <div class="col-md-3">
    <%= render 'layouts/user_bar' %>
  </div>
  <div class="col-md-9">
    <%= render 'layouts/tabs' %>

    <div class="feed">
          <%= render 'layouts/follower' %>
      </div>
  </div>
</div>

app/views/gists/index.html.erb
<div class="container">
<h1>Gists</h1>
<p>Gists live here</p>
</div>

app/views/home/index.html.erb
<div class="container">
  Welcome to Github
</div>

app/views/layouts/_follower.html.erb
<% @followers.each do |follower| %>
  <li>
    <div class="followers">
      <div class="thumbnail-avatar">
        <img class="follow-avatar" src="<%="#{follower.avatar}"%>">
      </div>
      <div class="username">
        <h4><%= link_to follower.login, followers_path %></h4>
      </div>
    </div>
    <hr>
  </li>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="nav-container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/"><%=image_tag("github-logo-2", class:"logo")%></a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

        </ul>
        <form class="navbar-form navbar-nav">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search GitHub">
          </div>
            <button type="submit" class="btn btn-default">Submit</button>
        </form>
        <ul class = "nav navbar-nav navbar-left">
          <li> <a href="/">Pull requests</a></li>
          <li> <a href="/">Issues</a></li>
          <li> <%= link_to "Gists", gists_path %></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li> <a href="/"><span class="glyphicon glyphicon-bell" aria-hidden="true"></span></a></li>
          <li class="dropdown"> <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span><span class="caret"></span></a>
            <ul class="dropdown-menu">
            <li><a href="#">New repository</a></li>
            <li><a href="#">Import repository</a></li>
            <li><a href="#">New gist</a></li>
            <li><a href="#">New organization</a></li>
          </ul>
          </li>
          <li class="dropdown">
          <% if current_user %>
            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#"><img class="avatar" src="https://avatars.githubusercontent.com/u/<%=current_user.uid%>"><span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li class="signed-in">Signed in as <%= "#{current_user.username}" %></li>
              <li role="separator" class="divider"></li>
              <li><a href='/users/<%="#{current_user.id}"%>'>Your profile</a></li>
              <li><a href="#">Your stars</a></li>
              <li><a href="#">Explore</a></li>
              <li><a href="#">Integrations</a></li>
              <li><a href="#">Help</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Settings</a></li>
              <li>
                <%= link_to "Sign out", logout_path, method: :delete %>
              </li>
            </ul>
          <% else %>
            <%= link_to "Sign In", "https://github.com/login/oauth/authorize?client_id=#{ENV["github_client_id"]}&scope=repo"%>
          <% end %>
          </li>
        </ul>
      </div><!-- /.navbar-collapse -->
    </div>
    </div><!-- /.container-fluid -->
  </nav>

app/views/layouts/_tabs.html.erb
<ul class="nav nav-tabs profile-options">
  <li role="presentation"><a href='/users/<%="#{current_user.id}"%>'>Overview</a></li>
  <li role="presentation"><a href="/repos">Repositories<span class="badge"><%=GithubRepo.for_user(current_user).count %></span></a></li>
  <li role="presentation"><a href="/stars">Stars<span class="badge"><%=GithubStar.for_user(current_user).count %></span></a></li>
  <li role="presentation"><a href="/followers">Followers<span class="badge"><%=GithubFollower.for_user(current_user).count %></span></a></li>
  <li role="presentation"><a href="/following">Following<span class="badge"><%=GithubFollowing.for_user(current_user).count %></span></a></li>
</ul>

app/views/layouts/_user_bar.html.erb
<ul class="user-info">
  <li><img class="profile-pic" src='https://avatars.githubusercontent.com/u/<%=current_user.uid%>'></li>
  <div class="profile-name">
    <li><h1 class="full-name"><%= current_user.name %></h1></li>
    <li class="username"><%= current_user.username %></li>
  </div>
  <hr>
  <li><span class="glyphicon glyphicon-map-marker"  aria-hidden="true"></span><%= current_user.location %></li>
  <li><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span><a href='mailto:<%="#{current_user.email}"%>'><%= current_user.email %></a></li>
  <li><span class="glyphicon glyphicon-time" aria-hidden="true"></span>Joined: <%= current_user.created_at.strftime("%b %e, %Y") %></li>
  <hr>
  <h4>Organizations</h4>
    <div class="avatar-group">
      <% GithubService.new.orgs(User.find(current_user.id)).each do |org| %>
          <img class="org-avatar" src="https://avatars.githubusercontent.com/u/<%=org[:id]%>">
      <% end %>
    </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiCurious</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/repos/index.html.erb
<div class="container container-profile">

  <div class="col-md-3">
    <%= render 'layouts/user_bar' %>
  </div>
  <div class="col-md-9">
    <%= render 'layouts/tabs' %>

    <div class="feed">

        <% @user_repos.each do |repo| %>
          <li>
            <h3><%= link_to repo.name, repos_path %></h3>
            <div class="description">
              <%= repo.description %>
            </div>
            <div class="lang-date">
              <div class="language">
                <%= repo.language %>
              </div>
              <div class="date">
                <%= "Updated on #{repo.date_format(repo.updated_at)} "%>
              </div>
            </div>
            <hr>
          </li>
        <% end %>
      </div>
  </div>
</div>

app/views/stars/index.html.erb
<div class="container container-profile">

  <div class="col-md-3">
    <%= render 'layouts/user_bar' %>
  </div>
  <div class="col-md-9">
    <%= render 'layouts/tabs' %>

    <div class="feed">

        <% @starred_repos.each do |repo| %>
          <li>
            <h3><%= link_to repo.full_name, stars_path %></h3>
            <div class="description">
              <%= repo.description %>
            </div>
            <div class="lang-date">
              <div class="language">
                <%= repo.language %>
              </div>
              <div class="date">
                <%= "Updated on #{repo.date_format(repo.updated_at)} "%>
              </div>
            </div>
            <hr>
          </li>
        <% end %>
      </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container container-profile">

  <div class="col-md-3">
    <%= render 'layouts/user_bar' %>
  </div>
  <div class="col-md-9">
    <%= render 'layouts/tabs' %>

    <div class="feed">
      <h3 class="contribution-activity">Contribution Activity</h3>
      <hr>
        <% @user_commits.each do |commit| %>
          <li class="commits">
            <h4><%= link_to commit.repo_name, repos_path %></h4>
            <div class="message">
              <%= "#{commit.message_hash.first[:message]}" %>
            </div>
            <hr>
          </li>
        <% end %>
      </div>
  </div>
</div>